// Code generated by protoc-gen-go. DO NOT EDIT.
// source: mongoOPService.proto

package v1

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/amsokol/protoc-gen-gotag/tagger"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type TYPE int32

const (
	TYPE_BOOLEAN   TYPE = 0
	TYPE_DOUBLE    TYPE = 1
	TYPE_INT32     TYPE = 2
	TYPE_INT64     TYPE = 3
	TYPE_STRING    TYPE = 4
	TYPE_TIMESTAMP TYPE = 5
)

var TYPE_name = map[int32]string{
	0: "BOOLEAN",
	1: "DOUBLE",
	2: "INT32",
	3: "INT64",
	4: "STRING",
	5: "TIMESTAMP",
}
var TYPE_value = map[string]int32{
	"BOOLEAN":   0,
	"DOUBLE":    1,
	"INT32":     2,
	"INT64":     3,
	"STRING":    4,
	"TIMESTAMP": 5,
}

func (x TYPE) String() string {
	return proto.EnumName(TYPE_name, int32(x))
}
func (TYPE) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_mongoOPService_74414df833faa524, []int{0}
}

type INDEX_ORDER int32

const (
	INDEX_ORDER_ASCENDING  INDEX_ORDER = 0
	INDEX_ORDER_DESCENDING INDEX_ORDER = 1
)

var INDEX_ORDER_name = map[int32]string{
	0: "ASCENDING",
	1: "DESCENDING",
}
var INDEX_ORDER_value = map[string]int32{
	"ASCENDING":  0,
	"DESCENDING": 1,
}

func (x INDEX_ORDER) String() string {
	return proto.EnumName(INDEX_ORDER_name, int32(x))
}
func (INDEX_ORDER) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_mongoOPService_74414df833faa524, []int{1}
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_mongoOPService_74414df833faa524, []int{0}
}
func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (dst *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(dst, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type TestWorldRequest struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *TestWorldRequest) Reset()         { *m = TestWorldRequest{} }
func (m *TestWorldRequest) String() string { return proto.CompactTextString(m) }
func (*TestWorldRequest) ProtoMessage()    {}
func (*TestWorldRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_mongoOPService_74414df833faa524, []int{1}
}
func (m *TestWorldRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestWorldRequest.Unmarshal(m, b)
}
func (m *TestWorldRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestWorldRequest.Marshal(b, m, deterministic)
}
func (dst *TestWorldRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestWorldRequest.Merge(dst, src)
}
func (m *TestWorldRequest) XXX_Size() int {
	return xxx_messageInfo_TestWorldRequest.Size(m)
}
func (m *TestWorldRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TestWorldRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TestWorldRequest proto.InternalMessageInfo

func (m *TestWorldRequest) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type TestWorldResponse struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *TestWorldResponse) Reset()         { *m = TestWorldResponse{} }
func (m *TestWorldResponse) String() string { return proto.CompactTextString(m) }
func (*TestWorldResponse) ProtoMessage()    {}
func (*TestWorldResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_mongoOPService_74414df833faa524, []int{2}
}
func (m *TestWorldResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestWorldResponse.Unmarshal(m, b)
}
func (m *TestWorldResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestWorldResponse.Marshal(b, m, deterministic)
}
func (dst *TestWorldResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestWorldResponse.Merge(dst, src)
}
func (m *TestWorldResponse) XXX_Size() int {
	return xxx_messageInfo_TestWorldResponse.Size(m)
}
func (m *TestWorldResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TestWorldResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TestWorldResponse proto.InternalMessageInfo

func (m *TestWorldResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type FieldValue struct {
	ValueType            TYPE     `protobuf:"varint,1,opt,name=valueType,proto3,enum=v1.TYPE" json:"valueType,omitempty"`
	FieldName            string   `protobuf:"bytes,2,opt,name=fieldName,proto3" json:"fieldName,omitempty"`
	IsUnique             bool     `protobuf:"varint,3,opt,name=isUnique,proto3" json:"isUnique,omitempty"`
	IsIndexed            bool     `protobuf:"varint,4,opt,name=isIndexed,proto3" json:"isIndexed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *FieldValue) Reset()         { *m = FieldValue{} }
func (m *FieldValue) String() string { return proto.CompactTextString(m) }
func (*FieldValue) ProtoMessage()    {}
func (*FieldValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_mongoOPService_74414df833faa524, []int{3}
}
func (m *FieldValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FieldValue.Unmarshal(m, b)
}
func (m *FieldValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FieldValue.Marshal(b, m, deterministic)
}
func (dst *FieldValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FieldValue.Merge(dst, src)
}
func (m *FieldValue) XXX_Size() int {
	return xxx_messageInfo_FieldValue.Size(m)
}
func (m *FieldValue) XXX_DiscardUnknown() {
	xxx_messageInfo_FieldValue.DiscardUnknown(m)
}

var xxx_messageInfo_FieldValue proto.InternalMessageInfo

func (m *FieldValue) GetValueType() TYPE {
	if m != nil {
		return m.ValueType
	}
	return TYPE_BOOLEAN
}

func (m *FieldValue) GetFieldName() string {
	if m != nil {
		return m.FieldName
	}
	return ""
}

func (m *FieldValue) GetIsUnique() bool {
	if m != nil {
		return m.IsUnique
	}
	return false
}

func (m *FieldValue) GetIsIndexed() bool {
	if m != nil {
		return m.IsIndexed
	}
	return false
}

type ListCollectionsResponse struct {
	Collections          []*Collection `protobuf:"bytes,1,rep,name=collections,proto3" json:"collections,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-" bson:"-"`
	XXX_unrecognized     []byte        `json:"-" bson:"-"`
	XXX_sizecache        int32         `json:"-" bson:"-"`
}

func (m *ListCollectionsResponse) Reset()         { *m = ListCollectionsResponse{} }
func (m *ListCollectionsResponse) String() string { return proto.CompactTextString(m) }
func (*ListCollectionsResponse) ProtoMessage()    {}
func (*ListCollectionsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_mongoOPService_74414df833faa524, []int{4}
}
func (m *ListCollectionsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListCollectionsResponse.Unmarshal(m, b)
}
func (m *ListCollectionsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListCollectionsResponse.Marshal(b, m, deterministic)
}
func (dst *ListCollectionsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListCollectionsResponse.Merge(dst, src)
}
func (m *ListCollectionsResponse) XXX_Size() int {
	return xxx_messageInfo_ListCollectionsResponse.Size(m)
}
func (m *ListCollectionsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListCollectionsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListCollectionsResponse proto.InternalMessageInfo

func (m *ListCollectionsResponse) GetCollections() []*Collection {
	if m != nil {
		return m.Collections
	}
	return nil
}

type Collection struct {
	Id                   string        `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string        `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Status               bool          `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`
	Host                 string        `protobuf:"bytes,4,opt,name=host,proto3" json:"host,omitempty"`
	FieldValues          []*FieldValue `protobuf:"bytes,5,rep,name=FieldValues,proto3" json:"FieldValues,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-" bson:"-"`
	XXX_unrecognized     []byte        `json:"-" bson:"-"`
	XXX_sizecache        int32         `json:"-" bson:"-"`
}

func (m *Collection) Reset()         { *m = Collection{} }
func (m *Collection) String() string { return proto.CompactTextString(m) }
func (*Collection) ProtoMessage()    {}
func (*Collection) Descriptor() ([]byte, []int) {
	return fileDescriptor_mongoOPService_74414df833faa524, []int{5}
}
func (m *Collection) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Collection.Unmarshal(m, b)
}
func (m *Collection) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Collection.Marshal(b, m, deterministic)
}
func (dst *Collection) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Collection.Merge(dst, src)
}
func (m *Collection) XXX_Size() int {
	return xxx_messageInfo_Collection.Size(m)
}
func (m *Collection) XXX_DiscardUnknown() {
	xxx_messageInfo_Collection.DiscardUnknown(m)
}

var xxx_messageInfo_Collection proto.InternalMessageInfo

func (m *Collection) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Collection) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Collection) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

func (m *Collection) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *Collection) GetFieldValues() []*FieldValue {
	if m != nil {
		return m.FieldValues
	}
	return nil
}

type CreateCollectionRequest struct {
	Collection           *Collection `protobuf:"bytes,1,opt,name=collection,proto3" json:"collection,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-" bson:"-"`
	XXX_unrecognized     []byte      `json:"-" bson:"-"`
	XXX_sizecache        int32       `json:"-" bson:"-"`
}

func (m *CreateCollectionRequest) Reset()         { *m = CreateCollectionRequest{} }
func (m *CreateCollectionRequest) String() string { return proto.CompactTextString(m) }
func (*CreateCollectionRequest) ProtoMessage()    {}
func (*CreateCollectionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_mongoOPService_74414df833faa524, []int{6}
}
func (m *CreateCollectionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateCollectionRequest.Unmarshal(m, b)
}
func (m *CreateCollectionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateCollectionRequest.Marshal(b, m, deterministic)
}
func (dst *CreateCollectionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateCollectionRequest.Merge(dst, src)
}
func (m *CreateCollectionRequest) XXX_Size() int {
	return xxx_messageInfo_CreateCollectionRequest.Size(m)
}
func (m *CreateCollectionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateCollectionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateCollectionRequest proto.InternalMessageInfo

func (m *CreateCollectionRequest) GetCollection() *Collection {
	if m != nil {
		return m.Collection
	}
	return nil
}

type CreateCollectionResponse struct {
	Collection           *Collection `protobuf:"bytes,1,opt,name=collection,proto3" json:"collection,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-" bson:"-"`
	XXX_unrecognized     []byte      `json:"-" bson:"-"`
	XXX_sizecache        int32       `json:"-" bson:"-"`
}

func (m *CreateCollectionResponse) Reset()         { *m = CreateCollectionResponse{} }
func (m *CreateCollectionResponse) String() string { return proto.CompactTextString(m) }
func (*CreateCollectionResponse) ProtoMessage()    {}
func (*CreateCollectionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_mongoOPService_74414df833faa524, []int{7}
}
func (m *CreateCollectionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateCollectionResponse.Unmarshal(m, b)
}
func (m *CreateCollectionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateCollectionResponse.Marshal(b, m, deterministic)
}
func (dst *CreateCollectionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateCollectionResponse.Merge(dst, src)
}
func (m *CreateCollectionResponse) XXX_Size() int {
	return xxx_messageInfo_CreateCollectionResponse.Size(m)
}
func (m *CreateCollectionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateCollectionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateCollectionResponse proto.InternalMessageInfo

func (m *CreateCollectionResponse) GetCollection() *Collection {
	if m != nil {
		return m.Collection
	}
	return nil
}

func init() {
	proto.RegisterType((*Empty)(nil), "v1.Empty")
	proto.RegisterType((*TestWorldRequest)(nil), "v1.TestWorldRequest")
	proto.RegisterType((*TestWorldResponse)(nil), "v1.TestWorldResponse")
	proto.RegisterType((*FieldValue)(nil), "v1.FieldValue")
	proto.RegisterType((*ListCollectionsResponse)(nil), "v1.ListCollectionsResponse")
	proto.RegisterType((*Collection)(nil), "v1.Collection")
	proto.RegisterType((*CreateCollectionRequest)(nil), "v1.CreateCollectionRequest")
	proto.RegisterType((*CreateCollectionResponse)(nil), "v1.CreateCollectionResponse")
	proto.RegisterEnum("v1.TYPE", TYPE_name, TYPE_value)
	proto.RegisterEnum("v1.INDEX_ORDER", INDEX_ORDER_name, INDEX_ORDER_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MongoOPServiceClient is the client API for MongoOPService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MongoOPServiceClient interface {
	TestWorld(ctx context.Context, in *TestWorldRequest, opts ...grpc.CallOption) (*TestWorldResponse, error)
	CreateCollection(ctx context.Context, in *CreateCollectionRequest, opts ...grpc.CallOption) (*CreateCollectionResponse, error)
	ListCollections(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListCollectionsResponse, error)
}

type mongoOPServiceClient struct {
	cc *grpc.ClientConn
}

func NewMongoOPServiceClient(cc *grpc.ClientConn) MongoOPServiceClient {
	return &mongoOPServiceClient{cc}
}

func (c *mongoOPServiceClient) TestWorld(ctx context.Context, in *TestWorldRequest, opts ...grpc.CallOption) (*TestWorldResponse, error) {
	out := new(TestWorldResponse)
	err := c.cc.Invoke(ctx, "/v1.MongoOPService/TestWorld", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mongoOPServiceClient) CreateCollection(ctx context.Context, in *CreateCollectionRequest, opts ...grpc.CallOption) (*CreateCollectionResponse, error) {
	out := new(CreateCollectionResponse)
	err := c.cc.Invoke(ctx, "/v1.MongoOPService/CreateCollection", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mongoOPServiceClient) ListCollections(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListCollectionsResponse, error) {
	out := new(ListCollectionsResponse)
	err := c.cc.Invoke(ctx, "/v1.MongoOPService/ListCollections", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MongoOPServiceServer is the server API for MongoOPService service.
type MongoOPServiceServer interface {
	TestWorld(context.Context, *TestWorldRequest) (*TestWorldResponse, error)
	CreateCollection(context.Context, *CreateCollectionRequest) (*CreateCollectionResponse, error)
	ListCollections(context.Context, *Empty) (*ListCollectionsResponse, error)
}

func RegisterMongoOPServiceServer(s *grpc.Server, srv MongoOPServiceServer) {
	s.RegisterService(&_MongoOPService_serviceDesc, srv)
}

func _MongoOPService_TestWorld_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TestWorldRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MongoOPServiceServer).TestWorld(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.MongoOPService/TestWorld",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MongoOPServiceServer).TestWorld(ctx, req.(*TestWorldRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MongoOPService_CreateCollection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCollectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MongoOPServiceServer).CreateCollection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.MongoOPService/CreateCollection",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MongoOPServiceServer).CreateCollection(ctx, req.(*CreateCollectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MongoOPService_ListCollections_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MongoOPServiceServer).ListCollections(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.MongoOPService/ListCollections",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MongoOPServiceServer).ListCollections(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _MongoOPService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "v1.MongoOPService",
	HandlerType: (*MongoOPServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "TestWorld",
			Handler:    _MongoOPService_TestWorld_Handler,
		},
		{
			MethodName: "CreateCollection",
			Handler:    _MongoOPService_CreateCollection_Handler,
		},
		{
			MethodName: "ListCollections",
			Handler:    _MongoOPService_ListCollections_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mongoOPService.proto",
}

func init() {
	proto.RegisterFile("mongoOPService.proto", fileDescriptor_mongoOPService_74414df833faa524)
}

var fileDescriptor_mongoOPService_74414df833faa524 = []byte{
	// 524 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x53, 0x4d, 0x6f, 0xd3, 0x4c,
	0x10, 0x8e, 0xf3, 0xd5, 0x78, 0xa2, 0x37, 0xaf, 0x59, 0x15, 0x6a, 0x85, 0x1e, 0x22, 0xab, 0xa0,
	0xa8, 0xa2, 0x81, 0xa6, 0x88, 0x03, 0x9c, 0xd2, 0xc4, 0x20, 0x43, 0x62, 0x47, 0x1b, 0x97, 0x8f,
	0x13, 0x32, 0xf1, 0x62, 0x2c, 0x39, 0xde, 0xd4, 0xbb, 0x89, 0xe8, 0x7f, 0x40, 0xfc, 0x40, 0x7e,
	0x0d, 0xda, 0xad, 0xe5, 0x35, 0x69, 0x38, 0x70, 0xda, 0x67, 0x66, 0x9e, 0x19, 0x3d, 0x33, 0x3b,
	0x03, 0x87, 0x2b, 0x9a, 0x46, 0xd4, 0x9b, 0x2f, 0x48, 0xb6, 0x8d, 0x97, 0x64, 0xb0, 0xce, 0x28,
	0xa7, 0xa8, 0xba, 0x3d, 0xef, 0x9e, 0x48, 0xb8, 0x3c, 0x8b, 0x48, 0x7a, 0x16, 0x51, 0x1e, 0x44,
	0x4f, 0x79, 0x10, 0x45, 0x24, 0xcb, 0x9f, 0x5b, 0xa6, 0x75, 0x00, 0x0d, 0x7b, 0xb5, 0xe6, 0x37,
	0xd6, 0x09, 0x18, 0x3e, 0x61, 0xfc, 0x03, 0xcd, 0x92, 0x10, 0x93, 0xeb, 0x0d, 0x61, 0x1c, 0x19,
	0x50, 0x5b, 0xb1, 0xc8, 0xd4, 0x7a, 0x5a, 0x5f, 0xc7, 0x02, 0x5a, 0x8f, 0xe0, 0x5e, 0x89, 0xc5,
	0xd6, 0x34, 0x65, 0x64, 0x0f, 0xed, 0x87, 0x06, 0xf0, 0x3a, 0x26, 0x49, 0xf8, 0x3e, 0x48, 0x36,
	0x04, 0x3d, 0x06, 0x7d, 0x2b, 0x80, 0x7f, 0xb3, 0x26, 0x92, 0xd6, 0x19, 0xb6, 0x06, 0xdb, 0xf3,
	0x81, 0xff, 0x69, 0x6e, 0x63, 0x15, 0x42, 0xc7, 0xa0, 0x7f, 0x15, 0x59, 0x6e, 0xb0, 0x22, 0x66,
	0x55, 0x96, 0x53, 0x0e, 0xd4, 0x85, 0x56, 0xcc, 0xae, 0xd2, 0xf8, 0x7a, 0x43, 0xcc, 0x5a, 0x4f,
	0xeb, 0xb7, 0x70, 0x61, 0x8b, 0xcc, 0x98, 0x39, 0x69, 0x48, 0xbe, 0x93, 0xd0, 0xac, 0xcb, 0xa0,
	0x72, 0x58, 0xef, 0xe0, 0x68, 0x1a, 0x33, 0x3e, 0xa6, 0x49, 0x42, 0x96, 0x3c, 0xa6, 0x29, 0x2b,
	0xb4, 0x3f, 0x83, 0xf6, 0x52, 0xb9, 0x4d, 0xad, 0x57, 0xeb, 0xb7, 0x87, 0x1d, 0x21, 0x4e, 0xb1,
	0x71, 0x99, 0x62, 0xfd, 0xd4, 0x00, 0x54, 0x0c, 0x75, 0xa0, 0x1a, 0x87, 0x79, 0xef, 0xd5, 0x38,
	0x44, 0x08, 0xea, 0xa9, 0x92, 0x2f, 0x31, 0x7a, 0x00, 0x4d, 0xc6, 0x03, 0xbe, 0x61, 0xb9, 0xee,
	0xdc, 0x12, 0xdc, 0x6f, 0x94, 0x71, 0x29, 0x58, 0xc7, 0x12, 0x0b, 0x41, 0x6a, 0x72, 0xcc, 0x6c,
	0x28, 0x41, 0xca, 0x8d, 0xcb, 0x14, 0xcb, 0x81, 0xa3, 0x71, 0x46, 0x02, 0x4e, 0x4a, 0x8a, 0xf3,
	0x0f, 0x1c, 0x00, 0x28, 0xe9, 0x52, 0xe4, 0xdd, 0xe6, 0x4a, 0x0c, 0xeb, 0x2d, 0x98, 0x77, 0x4b,
	0xe5, 0x93, 0xfa, 0xc7, 0x5a, 0xa7, 0x73, 0xa8, 0x8b, 0xff, 0x45, 0x6d, 0x38, 0xb8, 0xf4, 0xbc,
	0xa9, 0x3d, 0x72, 0x8d, 0x0a, 0x02, 0x68, 0x4e, 0xbc, 0xab, 0xcb, 0xa9, 0x6d, 0x68, 0x48, 0x87,
	0x86, 0xe3, 0xfa, 0x17, 0x43, 0xa3, 0x9a, 0xc3, 0x17, 0xcf, 0x8d, 0x9a, 0x60, 0x2c, 0x7c, 0xec,
	0xb8, 0x6f, 0x8c, 0x3a, 0xfa, 0x0f, 0x74, 0xdf, 0x99, 0xd9, 0x0b, 0x7f, 0x34, 0x9b, 0x1b, 0x8d,
	0xd3, 0x27, 0xd0, 0x76, 0xdc, 0x89, 0xfd, 0xf1, 0xb3, 0x87, 0x27, 0x36, 0x16, 0xd1, 0xd1, 0x62,
	0x6c, 0xbb, 0x13, 0x41, 0xae, 0xa0, 0x0e, 0xc0, 0xc4, 0x2e, 0x6c, 0x6d, 0xf8, 0x4b, 0x83, 0xce,
	0xec, 0x8f, 0xe3, 0x40, 0x2f, 0x41, 0x2f, 0xb6, 0x17, 0x1d, 0xca, 0x0d, 0xdc, 0x59, 0xf9, 0xee,
	0xfd, 0x1d, 0xef, 0x6d, 0xf3, 0x56, 0x05, 0x79, 0x60, 0xec, 0x8e, 0x06, 0x3d, 0x94, 0xed, 0xef,
	0x9f, 0x7d, 0xf7, 0x78, 0x7f, 0xb0, 0x28, 0xf8, 0x0a, 0xfe, 0xdf, 0x59, 0x4a, 0xa4, 0x8b, 0x14,
	0x79, 0x8e, 0x5d, 0x59, 0xfa, 0x2f, 0x4b, 0x6b, 0x55, 0xbe, 0x34, 0xe5, 0xf5, 0x5e, 0xfc, 0x0e,
	0x00, 0x00, 0xff, 0xff, 0x8e, 0x3f, 0xdc, 0xf8, 0xff, 0x03, 0x00, 0x00,
}
