// Code generated by protoc-gen-go. DO NOT EDIT.
// source: todo.proto

package v1

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"
import wrappers "github.com/golang/protobuf/ptypes/wrappers"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_todo_085e1802a66c7c2f, []int{0}
}
func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (dst *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(dst, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type Todo struct {
	Id                   string                `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string                `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description          *wrappers.StringValue `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	IsCompleted          bool                  `protobuf:"varint,4,opt,name=isCompleted,proto3" json:"isCompleted,omitempty"`
	IsCompletedWrapped   *wrappers.BoolValue   `protobuf:"bytes,5,opt,name=isCompletedWrapped,proto3" json:"isCompletedWrapped,omitempty"`
	CreatedAtWrapped     *timestamp.Timestamp  `protobuf:"bytes,6,opt,name=createdAtWrapped,proto3" json:"createdAtWrapped,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *Todo) Reset()         { *m = Todo{} }
func (m *Todo) String() string { return proto.CompactTextString(m) }
func (*Todo) ProtoMessage()    {}
func (*Todo) Descriptor() ([]byte, []int) {
	return fileDescriptor_todo_085e1802a66c7c2f, []int{1}
}
func (m *Todo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Todo.Unmarshal(m, b)
}
func (m *Todo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Todo.Marshal(b, m, deterministic)
}
func (dst *Todo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Todo.Merge(dst, src)
}
func (m *Todo) XXX_Size() int {
	return xxx_messageInfo_Todo.Size(m)
}
func (m *Todo) XXX_DiscardUnknown() {
	xxx_messageInfo_Todo.DiscardUnknown(m)
}

var xxx_messageInfo_Todo proto.InternalMessageInfo

func (m *Todo) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Todo) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Todo) GetDescription() *wrappers.StringValue {
	if m != nil {
		return m.Description
	}
	return nil
}

func (m *Todo) GetIsCompleted() bool {
	if m != nil {
		return m.IsCompleted
	}
	return false
}

func (m *Todo) GetIsCompletedWrapped() *wrappers.BoolValue {
	if m != nil {
		return m.IsCompletedWrapped
	}
	return nil
}

func (m *Todo) GetCreatedAtWrapped() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAtWrapped
	}
	return nil
}

type TodoList struct {
	Todos                []*Todo  `protobuf:"bytes,1,rep,name=todos,proto3" json:"todos,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TodoList) Reset()         { *m = TodoList{} }
func (m *TodoList) String() string { return proto.CompactTextString(m) }
func (*TodoList) ProtoMessage()    {}
func (*TodoList) Descriptor() ([]byte, []int) {
	return fileDescriptor_todo_085e1802a66c7c2f, []int{2}
}
func (m *TodoList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TodoList.Unmarshal(m, b)
}
func (m *TodoList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TodoList.Marshal(b, m, deterministic)
}
func (dst *TodoList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TodoList.Merge(dst, src)
}
func (m *TodoList) XXX_Size() int {
	return xxx_messageInfo_TodoList.Size(m)
}
func (m *TodoList) XXX_DiscardUnknown() {
	xxx_messageInfo_TodoList.DiscardUnknown(m)
}

var xxx_messageInfo_TodoList proto.InternalMessageInfo

func (m *TodoList) GetTodos() []*Todo {
	if m != nil {
		return m.Todos
	}
	return nil
}

type CreateRequest struct {
	Todo                 *Todo    `protobuf:"bytes,1,opt,name=todo,proto3" json:"todo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateRequest) Reset()         { *m = CreateRequest{} }
func (m *CreateRequest) String() string { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()    {}
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_todo_085e1802a66c7c2f, []int{3}
}
func (m *CreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRequest.Unmarshal(m, b)
}
func (m *CreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRequest.Marshal(b, m, deterministic)
}
func (dst *CreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRequest.Merge(dst, src)
}
func (m *CreateRequest) XXX_Size() int {
	return xxx_messageInfo_CreateRequest.Size(m)
}
func (m *CreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRequest proto.InternalMessageInfo

func (m *CreateRequest) GetTodo() *Todo {
	if m != nil {
		return m.Todo
	}
	return nil
}

type UpdateRequest struct {
	Todo                 *Todo    `protobuf:"bytes,1,opt,name=todo,proto3" json:"todo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateRequest) Reset()         { *m = UpdateRequest{} }
func (m *UpdateRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateRequest) ProtoMessage()    {}
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_todo_085e1802a66c7c2f, []int{4}
}
func (m *UpdateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateRequest.Unmarshal(m, b)
}
func (m *UpdateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateRequest.Marshal(b, m, deterministic)
}
func (dst *UpdateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateRequest.Merge(dst, src)
}
func (m *UpdateRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateRequest.Size(m)
}
func (m *UpdateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateRequest proto.InternalMessageInfo

func (m *UpdateRequest) GetTodo() *Todo {
	if m != nil {
		return m.Todo
	}
	return nil
}

type DeleteRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRequest) Reset()         { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()    {}
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_todo_085e1802a66c7c2f, []int{5}
}
func (m *DeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRequest.Unmarshal(m, b)
}
func (m *DeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRequest.Marshal(b, m, deterministic)
}
func (dst *DeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRequest.Merge(dst, src)
}
func (m *DeleteRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteRequest.Size(m)
}
func (m *DeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRequest proto.InternalMessageInfo

func (m *DeleteRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRequest) Reset()         { *m = GetRequest{} }
func (m *GetRequest) String() string { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()    {}
func (*GetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_todo_085e1802a66c7c2f, []int{6}
}
func (m *GetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRequest.Unmarshal(m, b)
}
func (m *GetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRequest.Marshal(b, m, deterministic)
}
func (dst *GetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRequest.Merge(dst, src)
}
func (m *GetRequest) XXX_Size() int {
	return xxx_messageInfo_GetRequest.Size(m)
}
func (m *GetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRequest proto.InternalMessageInfo

func (m *GetRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func init() {
	proto.RegisterType((*Empty)(nil), "v1.Empty")
	proto.RegisterType((*Todo)(nil), "v1.Todo")
	proto.RegisterType((*TodoList)(nil), "v1.TodoList")
	proto.RegisterType((*CreateRequest)(nil), "v1.CreateRequest")
	proto.RegisterType((*UpdateRequest)(nil), "v1.UpdateRequest")
	proto.RegisterType((*DeleteRequest)(nil), "v1.DeleteRequest")
	proto.RegisterType((*GetRequest)(nil), "v1.GetRequest")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TodoServiceClient is the client API for TodoService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TodoServiceClient interface {
	Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*Todo, error)
	Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*Todo, error)
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*Todo, error)
	List(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*TodoList, error)
	Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*Empty, error)
}

type todoServiceClient struct {
	cc *grpc.ClientConn
}

func NewTodoServiceClient(cc *grpc.ClientConn) TodoServiceClient {
	return &todoServiceClient{cc}
}

func (c *todoServiceClient) Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*Todo, error) {
	out := new(Todo)
	err := c.cc.Invoke(ctx, "/v1.TodoService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *todoServiceClient) Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*Todo, error) {
	out := new(Todo)
	err := c.cc.Invoke(ctx, "/v1.TodoService/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *todoServiceClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*Todo, error) {
	out := new(Todo)
	err := c.cc.Invoke(ctx, "/v1.TodoService/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *todoServiceClient) List(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*TodoList, error) {
	out := new(TodoList)
	err := c.cc.Invoke(ctx, "/v1.TodoService/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *todoServiceClient) Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/v1.TodoService/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TodoServiceServer is the server API for TodoService service.
type TodoServiceServer interface {
	Create(context.Context, *CreateRequest) (*Todo, error)
	Update(context.Context, *UpdateRequest) (*Todo, error)
	Get(context.Context, *GetRequest) (*Todo, error)
	List(context.Context, *Empty) (*TodoList, error)
	Delete(context.Context, *DeleteRequest) (*Empty, error)
}

func RegisterTodoServiceServer(s *grpc.Server, srv TodoServiceServer) {
	s.RegisterService(&_TodoService_serviceDesc, srv)
}

func _TodoService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TodoServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.TodoService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TodoServiceServer).Create(ctx, req.(*CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TodoService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TodoServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.TodoService/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TodoServiceServer).Update(ctx, req.(*UpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TodoService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TodoServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.TodoService/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TodoServiceServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TodoService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TodoServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.TodoService/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TodoServiceServer).List(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _TodoService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TodoServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.TodoService/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TodoServiceServer).Delete(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _TodoService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "v1.TodoService",
	HandlerType: (*TodoServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _TodoService_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _TodoService_Update_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _TodoService_Get_Handler,
		},
		{
			MethodName: "List",
			Handler:    _TodoService_List_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _TodoService_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "todo.proto",
}

func init() { proto.RegisterFile("todo.proto", fileDescriptor_todo_085e1802a66c7c2f) }

var fileDescriptor_todo_085e1802a66c7c2f = []byte{
	// 401 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x52, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0x8d, 0x1d, 0xdb, 0xa4, 0x63, 0x5a, 0xc1, 0x8a, 0x83, 0x65, 0x45, 0xad, 0xd9, 0x0b, 0x16,
	0x12, 0xae, 0x1a, 0xee, 0x48, 0x50, 0xa0, 0x12, 0xe2, 0xe4, 0x16, 0x38, 0xbb, 0xd9, 0x21, 0x5a,
	0xc9, 0xce, 0x2e, 0xf6, 0x24, 0x88, 0xdf, 0xe1, 0x87, 0xf8, 0x25, 0xb4, 0xbb, 0x32, 0xb1, 0x13,
	0x22, 0xf5, 0xb8, 0xef, 0xbd, 0x99, 0xf7, 0x66, 0x66, 0x01, 0x48, 0x09, 0x55, 0xe8, 0x56, 0x91,
	0x62, 0xfe, 0xf6, 0x2a, 0xbd, 0x58, 0x29, 0xb5, 0xaa, 0xf1, 0xd2, 0x22, 0xf7, 0x9b, 0xef, 0x97,
	0x24, 0x1b, 0xec, 0xa8, 0x6a, 0xb4, 0x13, 0xa5, 0xe7, 0xfb, 0x82, 0x9f, 0x6d, 0xa5, 0x35, 0xb6,
	0x9d, 0xe3, 0xf9, 0x23, 0x08, 0x3f, 0x34, 0x9a, 0x7e, 0xf1, 0xdf, 0x3e, 0x04, 0x77, 0x4a, 0x28,
	0x76, 0x06, 0xbe, 0x14, 0x89, 0x97, 0x79, 0xf9, 0x49, 0xe9, 0x4b, 0xc1, 0x9e, 0x41, 0x48, 0x92,
	0x6a, 0x4c, 0x7c, 0x0b, 0xb9, 0x07, 0x7b, 0x03, 0xb1, 0xc0, 0x6e, 0xd9, 0x4a, 0x4d, 0x52, 0xad,
	0x93, 0x69, 0xe6, 0xe5, 0xf1, 0x62, 0x5e, 0x38, 0xb7, 0xa2, 0x77, 0x2b, 0x6e, 0xa9, 0x95, 0xeb,
	0xd5, 0xd7, 0xaa, 0xde, 0x60, 0x39, 0x2c, 0x60, 0x19, 0xc4, 0xb2, 0xbb, 0x56, 0x8d, 0xae, 0x91,
	0x50, 0x24, 0x41, 0xe6, 0xe5, 0xb3, 0x72, 0x08, 0xb1, 0x4f, 0xc0, 0x06, 0xcf, 0x6f, 0x36, 0xb6,
	0x48, 0x42, 0x6b, 0x94, 0x1e, 0x18, 0xbd, 0x53, 0xaa, 0x76, 0x36, 0xff, 0xa9, 0x62, 0x1f, 0xe1,
	0xc9, 0xb2, 0xc5, 0x8a, 0x50, 0xbc, 0xa5, 0xbe, 0x53, 0x74, 0xa4, 0xd3, 0x5d, 0xbf, 0xc1, 0xf2,
	0xa0, 0x86, 0xbf, 0x84, 0x99, 0xd9, 0xd1, 0x67, 0xd9, 0x11, 0x3b, 0x87, 0xd0, 0x1c, 0xa3, 0x4b,
	0xbc, 0x6c, 0x9a, 0xc7, 0x8b, 0x59, 0xb1, 0xbd, 0x2a, 0x0c, 0x59, 0x3a, 0x98, 0xbf, 0x82, 0xd3,
	0x6b, 0x5b, 0x5f, 0xe2, 0x8f, 0x0d, 0x76, 0xc4, 0xe6, 0x10, 0x18, 0xc6, 0xae, 0x76, 0xa8, 0xb7,
	0xa8, 0x91, 0x7f, 0xd1, 0xe2, 0xc1, 0xf2, 0x0b, 0x38, 0x7d, 0x8f, 0x66, 0xc6, 0x5e, 0xbe, 0x77,
	0x36, 0x3e, 0x07, 0xb8, 0x41, 0x3a, 0xc2, 0x2e, 0xfe, 0x78, 0x10, 0x9b, 0x6e, 0xb7, 0xd8, 0x6e,
	0xe5, 0x12, 0xd9, 0x0b, 0x88, 0x5c, 0x58, 0xf6, 0xd4, 0x18, 0x8d, 0x82, 0xa7, 0xff, 0xbc, 0xf9,
	0xc4, 0x08, 0x5d, 0x4c, 0x27, 0x1c, 0x45, 0x1e, 0x09, 0x9f, 0xc3, 0xf4, 0x06, 0x89, 0x9d, 0x19,
	0x68, 0x17, 0x64, 0x4f, 0x12, 0xd8, 0x4d, 0x9e, 0x18, 0xcc, 0xfe, 0xc2, 0xf4, 0x71, 0x4f, 0x1b,
	0x82, 0x4f, 0x58, 0x0e, 0x91, 0x1b, 0xd3, 0xd9, 0x8d, 0x46, 0x4e, 0x77, 0x75, 0x7c, 0x72, 0x1f,
	0xd9, 0x03, 0xbe, 0xfe, 0x1b, 0x00, 0x00, 0xff, 0xff, 0x6e, 0xed, 0xc0, 0x9a, 0x22, 0x03, 0x00,
	0x00,
}
